"""MCP write tools for test suites — create and update regular (non-monitor) suites.

Monitor suites (``is_monitor=True``) are managed exclusively through the dedicated
monitors surface. ``resolve_test_suite`` already filters them out, so an
``update_test_suite`` call against a monitor-suite ID surfaces the unified
``not found or not accessible`` error.
"""

from __future__ import annotations

from typing import Any

from testgen.common.models import get_current_session, with_database_session
from testgen.common.models.test_definition import Severity
from testgen.common.models.test_suite import TestSuite
from testgen.mcp.exceptions import MCPUserError
from testgen.mcp.permissions import mcp_permission
from testgen.mcp.tools.common import (
    DocGroup,
    parse_severity,
    raise_validation_error,
    resolve_table_group,
    resolve_test_suite,
)
from testgen.mcp.tools.markdown import MdDoc

_DOC_GROUP = DocGroup.MANAGE

# Free-text + component fields are stored as ``NullIfEmptyString`` columns: writing ``""``
# to one becomes ``NULL`` in the DB. Normalize on the way in so the diff-renderer doesn't
# flag a phantom change (``before=None`` → ``after=""``) on a value that the DB will read
# back as identical to before.
_OPTIONAL_TEXT_ATTRS = (
    "test_suite_description",
    "component_key",
    "component_type",
    "component_name",
)


def _empty_to_none(value: str | None) -> str | None:
    return value if value else None


@with_database_session
@mcp_permission("edit")
def create_test_suite(
    table_group_id: str,
    test_suite_name: str,
    *,
    description: str | None = None,
    severity_default: str | None = None,
    export_to_observability: bool = False,
    component_key: str | None = None,
    component_type: str | None = "dataset",
    component_name: str | None = None,
    dq_score_exclude: bool = False,
) -> str:
    """Create a test suite under a table group.

    The new suite inherits the table group's project and connection.

    Args:
        table_group_id: UUID of the table group, e.g. from `list_table_groups`.
        test_suite_name: Display name for the suite.
        description: Optional free-text description.
        severity_default: Optional default severity applied to tests that do
            not set their own. Accepts `Fail` or `Warning`.
        export_to_observability: Whether to export test results to the
            configured DataOps Observability backend. Defaults to False.
        component_key: Component identifier in DataOps Observability.
        component_type: Component type in DataOps Observability
            (e.g. `dataset`). Defaults to `dataset`.
        component_name: Component display name in DataOps Observability.
        dq_score_exclude: Whether to exclude this suite's results from data
            quality scoring. Defaults to False.
    """
    name = test_suite_name.strip() if test_suite_name else ""
    errors: list[str] = []
    if not name:
        errors.append("test_suite_name: must not be empty.")
    parsed_severity: Severity | None = _parse_severity_field(severity_default, errors)
    if errors:
        raise_validation_error(errors, "Test suite creation rejected. No changes saved.")

    table_group = resolve_table_group(table_group_id)

    suite = TestSuite(
        project_code=table_group.project_code,
        connection_id=table_group.connection_id,
        table_groups_id=table_group.id,
        test_suite=name,
        test_suite_description=_empty_to_none(description),
        severity=parsed_severity.value if parsed_severity is not None else None,
        export_to_observability=export_to_observability,
        component_key=_empty_to_none(component_key),
        component_type=_empty_to_none(component_type),
        component_name=_empty_to_none(component_name),
        dq_score_exclude=dq_score_exclude,
        is_monitor=False,
    )
    session = get_current_session()
    session.add(suite)
    # Flush so the autogenerated ``id`` is available for the rendered response.
    session.flush()

    return _render_created_suite(suite, table_group_name=table_group.table_groups_name)


@with_database_session
@mcp_permission("edit")
def update_test_suite(
    test_suite_id: str,
    *,
    test_suite_name: str | None = None,
    description: str | None = None,
    severity_default: str | None = None,
    export_to_observability: bool | None = None,
    component_key: str | None = None,
    component_type: str | None = None,
    component_name: str | None = None,
    dq_score_exclude: bool | None = None,
) -> str:
    """Update fields on a test suite. Atomic — nothing saved unless every supplied value is valid.

    Args:
        test_suite_id: UUID of the test suite, e.g. from `list_test_suites`.
        test_suite_name: New display name.
        description: New free-text description. Pass an empty string to clear.
        severity_default: New default severity for tests that do not set their
            own. Accepts `Fail` or `Warning`.
        export_to_observability: Whether test results are exported to the
            configured DataOps Observability backend.
        component_key: Component identifier in DataOps Observability.
            Pass an empty string to clear.
        component_type: Component type in DataOps Observability
            (e.g. `dataset`). Pass an empty string to clear.
        component_name: Component display name in DataOps Observability.
            Pass an empty string to clear.
        dq_score_exclude: Whether this suite's results are excluded from data
            quality scoring.
    """
    supplied = {
        "test_suite_name": test_suite_name,
        "description": description,
        "severity_default": severity_default,
        "export_to_observability": export_to_observability,
        "component_key": component_key,
        "component_type": component_type,
        "component_name": component_name,
        "dq_score_exclude": dq_score_exclude,
    }
    if all(value is None for value in supplied.values()):
        raise MCPUserError("No fields supplied to update.")

    suite = resolve_test_suite(test_suite_id)

    # Validate every supplied field first; surface all errors at once.
    errors: list[str] = []
    updates: dict[str, Any] = {}

    if test_suite_name is not None:
        cleaned = test_suite_name.strip()
        if not cleaned:
            errors.append("test_suite_name: must not be empty.")
        else:
            updates["test_suite"] = cleaned

    if description is not None:
        updates["test_suite_description"] = _empty_to_none(description)

    if severity_default is not None:
        parsed = _parse_severity_field(severity_default, errors)
        if parsed is not None:
            updates["severity"] = parsed.value

    if export_to_observability is not None:
        updates["export_to_observability"] = export_to_observability
    if component_key is not None:
        updates["component_key"] = _empty_to_none(component_key)
    if component_type is not None:
        updates["component_type"] = _empty_to_none(component_type)
    if component_name is not None:
        updates["component_name"] = _empty_to_none(component_name)
    if dq_score_exclude is not None:
        updates["dq_score_exclude"] = dq_score_exclude

    if errors:
        raise_validation_error(errors, "Update rejected. No changes saved.")

    # Diff scoped to the attributes actually touched by this call.
    before = {attr: getattr(suite, attr, None) for attr in updates}
    for attr, value in updates.items():
        setattr(suite, attr, value)
    after = {attr: getattr(suite, attr, None) for attr in updates}
    changed = {attr for attr in before if before[attr] != after[attr]}

    doc = MdDoc()
    doc.heading(1, f"Test Suite `{suite.test_suite}` updated")
    doc.field("ID", str(suite.id), code=True)

    if not changed:
        doc.text("No fields changed — supplied values matched the current state.")
        return doc.render()

    suite.save()

    rows: list[list[object]] = []
    for attr in _DIFF_ORDER:
        if attr not in changed:
            continue
        rows.append([_DIFF_LABELS[attr], _render_field_value(before[attr]), _render_field_value(after[attr])])
    doc.table(["Field", "Before", "After"], rows, code=[0])
    return doc.render()


def _parse_severity_field(value: str | None, errors: list[str]) -> Severity | None:
    """Validate a ``severity_default`` arg; append a field-scoped bullet on failure."""
    if value is None:
        return None
    try:
        return parse_severity(value)
    except MCPUserError:
        valid = ", ".join(s.value for s in Severity)
        errors.append(f"severity_default: must be one of {valid} (got `{value}`).")
        return None


def _render_created_suite(suite: TestSuite, *, table_group_name: str) -> str:
    doc = MdDoc()
    doc.heading(1, f"Test Suite `{suite.test_suite}` created")
    doc.field("ID", str(suite.id), code=True)
    doc.field("Project", suite.project_code, code=True)
    doc.field("Table Group", f"{table_group_name} (`{suite.table_groups_id}`)")
    if suite.test_suite_description:
        doc.field("Description", suite.test_suite_description)
    if suite.severity:
        doc.field("Default severity", suite.severity)
    doc.field("Export to Observability", suite.export_to_observability)
    if suite.component_key:
        doc.field("Component key", suite.component_key)
    if suite.component_type:
        doc.field("Component type", suite.component_type)
    if suite.component_name:
        doc.field("Component name", suite.component_name)
    doc.field("Exclude from quality scoring", suite.dq_score_exclude)
    return doc.render()


# Order drives the diff-table rendering. Mirrors the update_test_suite arg order:
# observability + components grouped together, dq_score_exclude separate.
_DIFF_ORDER: tuple[str, ...] = (
    "test_suite",
    "test_suite_description",
    "severity",
    "export_to_observability",
    "component_key",
    "component_type",
    "component_name",
    "dq_score_exclude",
)

_DIFF_LABELS: dict[str, str] = {
    "test_suite": "Name",
    "test_suite_description": "Description",
    "severity": "Default severity",
    "export_to_observability": "Export to Observability",
    "component_key": "Component key",
    "component_type": "Component type",
    "component_name": "Component name",
    "dq_score_exclude": "Exclude from quality scoring",
}


def _render_field_value(value: Any) -> str | None:
    if isinstance(value, bool):
        return "Yes" if value else "No"
    if value is None or value == "":
        return None
    return str(value)
