SET SEARCH_PATH TO {SCHEMA_NAME};

ALTER TABLE auth_users
  ADD COLUMN latest_login TIMESTAMP,
  ALTER COLUMN username TYPE VARCHAR(256),
  ALTER COLUMN email TYPE VARCHAR(256),
  ALTER COLUMN name TYPE VARCHAR(256),
  DROP CONSTRAINT username_check;
