SET SEARCH_PATH TO {SCHEMA_NAME};

ALTER TABLE table_groups ADD COLUMN IF NOT EXISTS profile_flag_pii BOOLEAN DEFAULT TRUE;

ALTER TABLE data_column_chars
    ADD COLUMN IF NOT EXISTS excluded_data_element BOOLEAN,
    ADD COLUMN IF NOT EXISTS pii_flag VARCHAR(50);
