{{- if .Values.testgen.databaseDecryptSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.testgen.databaseDecryptSecret.name | quote }}
  labels:
    {{- include "testgen.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
type: Opaque
data:
  decrypt-salt: {{ randAlphaNum 32 | b64enc | quote }}
  decrypt-password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
