{{- if .Values.testgen.authSecrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.testgen.authSecrets.name | quote }}
  labels:
    {{- include "testgen.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-1"
type: Opaque
data:
  decrypt-salt: {{ randAlphaNum 32 | b64enc | quote }}
  decrypt-password: {{ randAlphaNum 32 | b64enc | quote }}
  jwt-hashing-key: {{ randBytes 32 | b64enc | quote }}
{{- end }}
