name: Publish Charts
description: Push charts to GitHub Pages
inputs:
  github-token:
    description: 'GitHub token for pushing to gh-pages branch'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v4.2.0

    - name: Add Helm Repos for Dependencies
      shell: bash
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      with:
        charts_dir: deploy/charts
        skip_existing: 'true'
        packages_with_index: 'true'
      env:
        CR_TOKEN: '${{ inputs.github-token }}'
