DELETE FROM test_definitions
WHERE test_suite_id = :TEST_SUITE_ID ::UUID
  -- Delete old autogenerated tests
  AND last_auto_gen_date < :RUN_DATE
  -- Ignore manual tests
  AND last_auto_gen_date IS NOT NULL
  -- Ignore locked tests
  AND lock_refresh = 'N';
